---
title: Voeg een variabele toe in Scratch
hero_image: afbeeldingen / banner.png
description: How to add a variable in Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Maak een variabele
