---
title: Voeg een variabele toe in Scratch
hero_image: images/banner.png
description: Hoe voeg je een variabele in Scratch 3 toe
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Maak een variabele
