---
title: Scratch এ একটি variable যুক্ত করুন
hero_image: images/banner.png
description: কিভাবে scratch 3 তে একটি variable যোগ করা যায়
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: একটি variable তৈরি করুন
