---
title: Legg til en variabel i Scratch
hero_image: images/banner.png
description: Hvordan legge til en variabel i Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Lag en variabel
