---
title: スクラッチに変数を追加する
hero_image: images/banner.png
description: Scratch 3に変数を追加する方法
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: 変数を作成する
