---
title: Add a variable in Scratch
hero_image: images/banner.png
description: Cách thêm biến trong Scratch 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Create a variable
