---
title: Tilføj en variabel i Scratch
hero_image: images/banner.png
description: Sådan tilføjes en variabel i Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Opret en variabel
