---
title: Adicionar uma vari치vel no Scratch
hero_image: imagens / banner.png
description: Como adicionar uma vari치vel no Scratch 3
original_url:
theme: prot칩tipo de cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Criar uma vari치vel
