---
title: Dodaj varijablu u Scratchu
hero_image: images/banner.png
description: Kako dodati varijablu u Scratchu 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Kreiraj varijablu
