---
title: Lis채채 muuttuja Scratchissa
hero_image: images/banner.png
description: Kuinka lis채t채 muuttuja Scratch 3:ssa
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Luo muuttuja
