---
title: یک متغیر در اسکرچ اضافه کنید
hero_image: images/banner.png
description: How to add a variable in Scratch 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: یک متغیر ایجاد کنید
