---
title: یک متغیر در اسکرچ اضافه کنید
hero_image: images/banner.png
description: چگونه یک متغیر در اسکرچ 3 اضافه کنید
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: یک متغیر ایجاد کنید
