---
title: Magdagdag ng variable sa Scratch
hero_image: images/banner.png
description: Paano magdagdag ng isang variable sa Scratch 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Lumikha ng isang variable
