---
title: Añadir una variable en Scratch
hero_image: images/banner.png
description: Cómo añadir una variable en Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Crear una variable
