---
title: Ychwanegu newidyn yn Scratch
hero_image: images/banner.png
description: Ychwanegu newidyn yn Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Creu newidyn
