---
title: Füge eine Variable in Scratch hinzu
hero_image: images/banner.png
description: Wie man eine Variable in Scratch 3 hinzufügt
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Erstelle eine Variable
