---
title: Füge eine Variable in Scratch hinzu
hero_image: images/banner.png
description: How to add a variable in Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Erstelle eine Variable
