---
title: Adăugarea unei variabile în Scratch
hero_image: images/banner.png
description: Cum să adaugi o variabilă în Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Creează o variabilă
