---
title: Adicione uma variável no Scratch
hero_image: images/banner.png
description: Como adicionar uma variável no Scratch 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Criar uma variável
