---
title: Přidání proměnné v aplikaci Scratch
hero_image: images/banner.png
description: Jak přidat proměnnou v aplikaci Scratch 3
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Vytvoř proměnnou
