---
title: Adj hozzá egy változót a Scratchben
hero_image: images/banner.png
description: Hogyan adj hozzá egy változót a Scratch 3-ban
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Hozz létre egy változót
