---
title: Muutuja lisamine Scratchis
hero_image: images/banner.png
description: Kuidas lisada muutujat Scratch 3-s
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Loo muutuja
