---
title: Dodaj zmienną w Scratchu
hero_image: images/banner.png
description: Jak dodać zmienną w Scratchu 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Stwórz zmienną
