---
title: Pridanie premennej v jazyku Scratch
hero_image: images / banner.png
description: Ako pridať premennú v Scratch 3
original_url:
theme: cc-prototyp
duration: 1 #1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Vytvorte premennú
