---
title: Ajoute une variable dans Scratch
hero_image: images/banner.png
description: Comment ajouter une variable dans Scratch 3
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Créer une variable
